name: genesis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.13.*
  - pip
  - pytorch
  - torchvision
  - pyyaml
  - tensorboard
  - jsonschema
  - jsonschema-gentypes
  - tensordict
  - numpy
  - pygame
  - pip:
      - genesis-world==0.3.*
      - rsl-rl-lib==3.3.*
