[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "servobot-rl-genesis"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
  "numpy",
  "torch",
  "torchvision",
  "pyyaml",
  "tensorboard>=2.20.0",
  "jsonschema",
  "jsonschema-gentypes",
  "tensordict",
  "numpy",
  "pygame",
  "genesis-world @ git+https://github.com/Genesis-Embodied-AI/Genesis.git",
  "rsl-rl-lib==5.*",
  "setuptools==81.0.0",
]

[project.scripts]
train = "scripts.train:main"
evaluate = "scripts.eval:main"
update_schema = "scripts.update_schema:main"
onnx = "scripts.onnx:main"


[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*", "src*"]
