# yaml-language-server: $schema=./schemas/config.json
runner:
  class_name: DistillationRunner
  num_steps_per_env: 512
  save_interval: 100
  seed: 1
  obs_groups: { "policy": ["policy"], "teacher": ["policy", "teacher"] }
  experiment_name: servobot
  logger: tensorboard
  neptune_project: legged_gym
  wandb_project: legged_gym
  max_iterations: 1000
  run_name: ""

  policy:
    class_name: StudentTeacherRecurrent
    activation: elu
    student_obs_normalization: true
    teacher_obs_normalization: true
    student_hidden_dims: [512, 256, 128]
    teacher_hidden_dims: [512, 256, 128]
    init_noise_std: 1.0

  algorithm:
    class_name: Distillation
    learning_rate: 0.001
    num_learning_epochs: 5
    gradient_length: 15
    max_grad_norm: 1.0
    loss_type: mse
    optimizer: adam

env:
  class_name: ServobotEnv
  robot_description_path: robots/servobot_description/urdf/robot.urdf
  robot_description_type: URDF
  joints:
    bl_bot: 0.1
    bl_hip: 0.2
    bl_top: -1.0
    br_bot: -0.1
    br_hip: -0.2
    br_top: 1.0
    fl_bot: 0.1
    fl_hip: -0.2
    fl_top: -0.6
    fr_bot: -0.1
    fr_hip: 0.2
    fr_top: 0.6
  base_init_pos: [0.0, 0.0, 0.2]
  base_init_quat: [1.0, 0.0, 0.0, 0.0]
  episode_length: 20.0
  resampling_time: 4.0
  action_scale: 0.25
  simulate_action_latency: True
  clip_actions: 100.0
  dt: 0.02
  termination_if_pitch_greater_than: 0.7
  termination_if_roll_greater_than: 0.7

commands:
  lin_vel_x: [0.2, 1.0]
  lin_vel_y: [0.0, 0.0]
  ang_vel_z: [0.0, 0.0]

obs:
  num_obs: 39
  num_teacher_obs: 6
  scales:
    lin_vel_x: 2.0
    lin_vel_y: 2.0
    ang_vel_z: 0.25
    dof_pos: 1.0
    dof_vel: 0.5

reward:
  tracking_sigma: 0.2
  rewards:
    tracking_lin_vel: 10.0
    tracking_ang_vel: 5.0
    lin_vel_z: -1.0
    roll_angle: -2.0
    pitch_angle: -5.0
    base_height: -50.0
    action_rate: -0.01
    similar_to_default: -0.1
    energy: 0.0
    survival: 0.1
  targets:
    base_height: .25
