phase1:
  name: "Slow Walking"
  description: "The robot learns to walk slowly at 0.2 m/s. Succeeds when it can maintain this speed for an average of 15 seconds."
  success_criteria:
    target_lin_vel_x: 0.2
    avg_iteration_len: 15.0
    max_episodes: 7000
  rewards:
    tracking_lin_vel: 8.0
    tracking_ang_vel: 4.0
    lin_vel_z: -0.5
    roll_angle: -1.0
    pitch_angle: -3.0
  commands: 
    lin_vel_x: [0.2, 0.2]
    lin_vel_y: [0.0, 0.0]
    ang_vel_z: [0.0, 0.0]

phase2:
  name: "Moderate Walking"
  description: "The robot learns to walk at a moderate speed of 0.5 m/s. Succeeds when it can maintain this speed for an average of 15 seconds."
  success_criteria:
    target_lin_vel_x: 0.5
    avg_iteration_len: 15.0
    max_episodes: 10000
  rewards:


phase3:
  name: "Fast Walking"
  description: "The robot learns to walk quickly at 1.0 m/s. Succeeds when it can maintain this speed for an average of 15 seconds."
  success_criteria:
    target_lin_vel_x: 1.0
    avg_iteration_len: 15.0
    max_episodes: 15000
  rewards: 

  commands: 
    speed: [.9, 1.0]
    ang_vel_z: [0.0, 0.0]


  